import fs from 'fs';
import path from 'path';
import url from 'url';
import dotenv from 'dotenv';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
dotenv.config({ path: path.join(root, '.env') });

const apiBase = process.env.API_BASE_URL || 'http://localhost:5000';
const outDir = path.join(root, 'src', 'app', 'core');
const outFile = path.join(outDir, 'env.generated.ts');
const content = `// AUTO-GENERATED by tools/inject-env.mjs\nexport const API_BASE_URL = '${apiBase}';\n`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, content, 'utf-8');
console.log(`Generated ${path.relative(root, outFile)} with API_BASE_URL=${apiBase}`);

