#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint-staged
dotnet format pipelane-api/Pipelane.sln --verify-no-changes
npx --yes tsc@5.8.3 --project pipelane-front/tsconfig.json --pretty false --noEmit
