name: Docker Build

on:
  push:
    branches: [ main, master ]
    paths:
      - 'pipelane-api/**'
      - 'pipelane-front/**'
      - 'docker-compose.yml'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: pipelane-api
          file: pipelane-api/Dockerfile
          push: false
          tags: pipelane-api:ci
      - name: Build Frontend image
        uses: docker/build-push-action@v6
        with:
          context: pipelane-front
          file: pipelane-front/Dockerfile
          push: false
          tags: pipelane-front:ci

